#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://server.nippon.workers.dev/ccache/mido/ccache.tar.gz

cd /tmp # Where to download cccahe
time curl -O --max-filesize 0 $url || aria2c $url
time tar xf /tmp/ccache.tar.gz
