#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://server.nippon.workers.dev/ccache/mido/ccache.tar.gz

cd /tmp # Where to download cccahe
curl -O $url || curl -O $url
