#!/bin/bash

MANIFEST=git://github.com/StyxProject/manifest.git
BRANCH=R

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name nnippon
git config --global user.email adameyyad999@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs
cd build/soong && git remote add d https://github.com/SyntatiX-OS/build_soong -f && git cherry-pick 781bd3afedb8891ddbeab6f96555db68ca1a2ad3^..470a3a74636831eb89f3c274897a1483761e9079 && cd ../..
find hardware/ril/libril external/motorola/faceunlock .repo/ -delete
git clone https://github.com/nnippon/android_hardware_samsung --single-branch -b aosp --depth=1 hardware/samsung
git clone https://github.com/nnippon/android_device_samsung_j6primelte --single-branch -b styx --depth=1 device/samsung/j6primelte
git clone https://github.com/nnippon/android_vendor_samsung-common --depth=1 vendor/samsung
git clone https://github.com/nnippon/android_device_samsung_msm8917-common --depth=1 device/samsung/msm8917-common
git clone https://github.com/nnippon/android_kernel_samsung_msm8917 --depth=1 kernel/samsung/msm8917
git clone https://github.com/lostark13/vendor_MiuiCamera --depth=1 vendor/MiuiCamera
git clone https://gitlab.com/crdroidandroid/android_external_moto_faceunlock.git --single-branch -b 11.0 externel/motorola/faceunlock
