#!/bin/bash

cd /tmp/prebuilts/tools-ancient/linux-x86/bin/ccache

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

time curl --upload-file ccache.tar.gz https://transfer.sh/
